[development]
address = "localhost"
port = 8000
workers = 1
keep_alive = 5
log = "normal"
limits = { forms = 32768 }

[staging]
address = "localhost"
port = 8000
workers = 1
keep_alive = 5
log = "normal"
limits = { forms = 32768 }

[production]
address = "localhost"
port = 8000
workers = 1
keep_alive = 5
limits = { forms = 32768 }